### ISSUE TITLE
Clone Discord UI

### ISSUE THREAD

**Issue by Kyurenpoto** [Kyurenpoto/ChatExercise#12]
* [x] Create a dark-themed main window
* [x] Divides the screen into large pieces for placing controls easily
* [x] Divide each part of the splitted screen again and place the controls
